# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  webapp:
    build: .
    restart: always
    ports:
      - 8081:8081
    environment:
      PORT: 8081
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      MONGO_DBNAME: nodemongo
