set -e

echo "=> CREATE STANDARD USER $MONGO_APPLICATION_USERNAME for $MONGO_INITDB_DATABASE"
echo "=> CONN URL SHOULD BE mongodb://${MONGO_APPLICATION_USERNAME}:${MONGO_APPLICATION_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}"
mongo <<EOF
use $MONGO_INITDB_DATABASE
db.createUser({
  user: "$MONGO_APPLICATION_USERNAME",
  pwd: "$MONGO_APPLICATION_PASSWORD",
  roles: [
    { role: "readWrite", db: "nodemongo" }
  ]
})
EOF